// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZW1N04UnqhrDWUhBkA1y-BWk0EtD9iGc',
    appId: '1:452763863056:web:49b7c2ce680ed06a496295',
    messagingSenderId: '452763863056',
    projectId: 'learn-flutter-suman',
    authDomain: 'learn-flutter-suman.firebaseapp.com',
    storageBucket: 'learn-flutter-suman.appspot.com',
    measurementId: 'G-0Z29HJ1HGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNhJIifux1LLBZtQL7h6hq-RVs3F1M_hE',
    appId: '1:452763863056:android:c210c7941448f53e496295',
    messagingSenderId: '452763863056',
    projectId: 'learn-flutter-suman',
    storageBucket: 'learn-flutter-suman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjCj0OmO9dZFfcD1_IRc9cLkSvgzSSwwM',
    appId: '1:452763863056:ios:a93b53fbb28a9767496295',
    messagingSenderId: '452763863056',
    projectId: 'learn-flutter-suman',
    storageBucket: 'learn-flutter-suman.appspot.com',
    iosClientId: '452763863056-boc0k60l50s5dguenpfgiahmhkc8o2ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjCj0OmO9dZFfcD1_IRc9cLkSvgzSSwwM',
    appId: '1:452763863056:ios:a93b53fbb28a9767496295',
    messagingSenderId: '452763863056',
    projectId: 'learn-flutter-suman',
    storageBucket: 'learn-flutter-suman.appspot.com',
    iosClientId: '452763863056-boc0k60l50s5dguenpfgiahmhkc8o2ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnfirebase',
  );
}
